nohup: ignoring input
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<new_date() done, defined at /root/ilyasdev/MasterTask/main.py:18> exception=OperationalError('no such table: tasks_table7220161823')>
Traceback (most recent call last):
  File "/root/ilyasdev/MasterTask/main.py", line 34, in new_date
    task_user = await sql.get_today_tasks_sql(user[0])
  File "/root/ilyasdev/MasterTask/app/database/sqlite_db.py", line 55, in get_today_tasks_sql
    return cur.execute(f"SELECT * FROM {'tasks_table'+str(tg_id)} WHERE date = ?", (str(today), )).fetchall()
sqlite3.OperationalError: no such table: tasks_table7220161823
Cause exception while process update id=474061512 by bot id=8185190653
OperationalError: near "table": syntax error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/middlewares/user_context.py", line 49, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/root/ilyasdev/MasterTask/app/handlers.py", line 74, in stop_add_task_handler
    await sql.create_new_table_sql(tasks_ls, callback.from_user.id)
  File "/root/ilyasdev/MasterTask/app/database/sqlite_db.py", line 49, in create_new_table_sql
    cur.execute("UPDATE clients SET table = ? WHERE id = ?", ('1', tg_id, ))
sqlite3.OperationalError: near "table": syntax error
Cause exception while process update id=474061513 by bot id=8185190653
OperationalError: duplicate column name: 2+2
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/middlewares/user_context.py", line 49, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/root/ilyasdev/MasterTask/app/handlers.py", line 74, in stop_add_task_handler
    await sql.create_new_table_sql(tasks_ls, callback.from_user.id)
  File "/root/ilyasdev/MasterTask/app/database/sqlite_db.py", line 42, in create_new_table_sql
    cur.execute(f"ALTER TABLE {'tasks_table'+str(tg_id)} ADD COLUMN [{task}] TEXT DEFAULT '0'")
sqlite3.OperationalError: duplicate column name: 2+2
Received SIGTERM signal
